export enum Resource {
  PRODUCTS = 'PRODUCTS',
  CATEGORIES = 'CATEGORIES',
  ORDERS = 'ORDERS',
  SETTINGS = 'SETTINGS',
  TEAM = 'TEAM',
  PAGES = 'PAGES',
  CUSTOMERS = 'CUSTOMERS',
  ANALYTICS = 'ANALYTICS',
}
